import Foundation

/// What the user asked for. Both AI providers build their requests from this,
/// so the count, exclusion, and naming rules live in one place.
nonisolated enum PlaylistPrompt: Sendable {
    case theme(String)
    case seed(SongMetadata)

    var defaultPlaylistName: String {
        switch self {
        case .theme(let theme):
            let collapsed = theme.split(whereSeparator: \.isWhitespace).joined(separator: " ")
            let titled = collapsed.prefix(1).uppercased() + collapsed.dropFirst()
            let trimmed = titled.count > 60 ? String(titled.prefix(60)) + "\u{2026}" : titled
            return "\u{1F3B5} \(trimmed)"
        case .seed(let seed):
            return "\u{1F3B5} Inspired by \(seed.title)"
        }
    }

    var playlistDescription: String {
        switch self {
        case .theme(let theme):
            "Generated by MusicAI from theme: \(theme)"
        case .seed(let seed):
            "Generated by MusicAI from \"\(seed.title)\" by \(seed.artistName)"
        }
    }

    /// The user message sent to the model.
    func userMessage(count: Int, excluding: [SongItem]) -> String {
        var lines: [String] = []

        switch self {
        case .theme(let theme):
            lines.append("Musical theme: \(theme)")
            lines.append("Return exactly \(count) songs.")
        case .seed(let seed):
            lines.append(seed.promptContext())
            lines.append("Generate exactly \(count) songs with a similar vibe, genre, and energy.")
            lines.append("Do NOT include the seed song itself in the results.")
        }

        if !excluding.isEmpty {
            lines.append("")
            lines.append("Do NOT suggest any of these songs (already in the playlist or unavailable on Apple Music):")
            lines.append(contentsOf: excluding.map { "- \"\($0.title)\" by \($0.artist)" })
        }

        return lines.joined(separator: "\n")
    }

    /// True when the model returned the seed song despite being told not to.
    func isSeed(_ item: SongItem) -> Bool {
        guard case .seed(let seed) = self else { return false }
        return MusicKitService.normalized(item.title) == MusicKitService.normalized(seed.title) &&
            MusicKitService.artistsMatch(
                MusicKitService.normalized(item.artist),
                MusicKitService.normalized(seed.artistName)
            )
    }
}
