import Foundation

/// What the user originally asked for. Codable so History can regenerate or refine it later.
nonisolated enum PlaylistPrompt: Codable, Sendable {
    case theme(String)
    case seed(SongMetadata)
    /// Two or more seed songs blended into one playlist.
    case blend([SongMetadata])

    var defaultPlaylistName: String {
        switch self {
        case .theme(let theme):
            let collapsed = theme.split(whereSeparator: \.isWhitespace).joined(separator: " ")
            let titled = collapsed.prefix(1).uppercased() + collapsed.dropFirst()
            return "\u{1F3B5} \(Self.truncated(titled))"
        case .seed(let seed):
            return "\u{1F3B5} Inspired by \(seed.title)"
        case .blend(let seeds):
            let titles = seeds.prefix(2).map(\.title).joined(separator: " \u{00D7} ")
            let extra = seeds.count > 2 ? " +\(seeds.count - 2)" : ""
            return "\u{1F3B5} Mash-up: \(Self.truncated(titles + extra))"
        }
    }

    private static func truncated(_ text: String, limit: Int = 60) -> String {
        text.count > limit ? String(text.prefix(limit)) + "\u{2026}" : text
    }

    var playlistDescription: String {
        switch self {
        case .theme(let theme):
            "Generated by MusicAI from theme: \(theme)"
        case .seed(let seed):
            "Generated by MusicAI from \"\(seed.title)\" by \(seed.artistName)"
        case .blend(let seeds):
            "Generated by MusicAI from a mash-up of " +
                seeds.map { "\"\($0.title)\" by \($0.artistName)" }.formatted(.list(type: .and))
        }
    }

    /// Short text for History rows and headers.
    var summary: String {
        switch self {
        case .theme(let theme):
            theme
        case .seed(let seed):
            "Inspired by \(seed.title) \u{2013} \(seed.artistName)"
        case .blend(let seeds):
            "Mash-up of " + seeds.map(\.title).formatted(.list(type: .and))
        }
    }

    /// The opening lines of the user message: what to generate and how many.
    func baseLines(count: Int) -> [String] {
        switch self {
        case .theme(let theme):
            ["Musical theme: \(theme)", "Return exactly \(count) songs."]
        case .seed(let seed):
            [
                seed.promptContext(),
                "Generate exactly \(count) songs with a similar vibe, genre, and energy.",
                "Do NOT include the seed song itself in the results."
            ]
        case .blend(let seeds):
            ["Blend these \(seeds.count) seed songs from the listener's library into one playlist:"] +
                seeds.enumerated().flatMap { index, seed in ["", "Seed \(index + 1):", seed.promptContext()] } +
                [
                    "",
                    "Generate exactly \(count) songs. Mix songs that sit close to each seed with songs that bridge their styles, and spread the playlist fairly across all the seeds.",
                    "Do NOT include any of the seed songs themselves."
                ]
        }
    }

    /// True when the model returned the seed song despite being told not to.
    func isSeed(_ item: SongItem) -> Bool {
        let seeds: [SongMetadata] = switch self {
        case .theme: []
        case .seed(let seed): [seed]
        case .blend(let seeds): seeds
        }
        let title = MusicKitService.normalized(item.title)
        let artist = MusicKitService.normalized(item.artist)
        return seeds.contains { seed in
            title == MusicKitService.normalized(seed.title) &&
                MusicKitService.artistsMatch(artist, MusicKitService.normalized(seed.artistName))
        }
    }
}
