import Foundation
import MusicKit

struct ResolvedSong: Sendable {
    let index: Int
    let song: Song?
}

actor MusicKitService {
    enum MusicKitError: LocalizedError {
        case notAuthorized
        case playlistCreationFailed(String)

        var errorDescription: String? {
            switch self {
            case .notAuthorized:
                "Music access not authorized. Please allow access in Settings."
            case .playlistCreationFailed(let detail):
                "Failed to create playlist: \(detail)"
            }
        }
    }

    func requestAuthorization() async throws {
        let status = await MusicAuthorization.request()
        guard status == .authorized else {
            throw MusicKitError.notAuthorized
        }
    }

    func resolveAndCreatePlaylist(
        songs: [SongItem],
        theme: String,
        onSongResolved: @Sendable (Int, Bool, Artwork?) -> Void
    ) async throws -> String {
        try await requestAuthorization()

        let resolvedSongs = try await resolveSongs(songs, onSongResolved: onSongResolved)

        let playlistName = "\u{1F3B5} \(theme)"
        let description = "Generated by MusicAI from theme: \(theme)"

        let library = MusicLibrary.shared
        let playlist = try await library.createPlaylist(
            name: playlistName,
            description: description,
            items: resolvedSongs
        )

        return playlist.name
    }

    private func resolveSongs(
        _ songs: [SongItem],
        onSongResolved: @Sendable (Int, Bool, Artwork?) -> Void
    ) async throws -> [Song] {
        var resolved: [Song] = []

        for (index, song) in songs.enumerated() {
            let result = try await searchSong(title: song.title, artist: song.artist)
            let found = result != nil
            if let result {
                resolved.append(result)
            }
            onSongResolved(index, found, result?.artwork)
        }

        return resolved
    }

    private func searchSong(title: String, artist: String) async throws -> Song? {
        var request = MusicCatalogSearchRequest(
            term: "\(title) \(artist)",
            types: [Song.self]
        )
        request.limit = 3

        let response = try await request.response()

        if let exact = response.songs.first(where: { song in
            song.title.localizedCaseInsensitiveCompare(title) == .orderedSame &&
            song.artistName.localizedCaseInsensitiveContains(artist)
        }) {
            return exact
        }

        return response.songs.first
    }
}
